//
//  CommentModel.h
//  Floral
//
//  Created by 思 彭 on 16/9/23.
//  Copyright © 2016年 思 彭. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface WriterModel : NSObject


/**
 "articleCount": 0,
 "attentionCount": 0,
 "attentioned": false,
 "auth": "",
 "bbsCount": 0,
 "birthday": "",
 "championM": false,
 "championW": false,
 "championY": false,
 "city": "",
 "content": "",
 "countryCode": "",
 "createDate": "",
 "dingYue": false,
 "email": "",
 "experience": 0,
 "fansCount": 0,
 "gag": false,
 "gagBeginDate": "",
 "gagEndDate": "",
 "headImg": "http://q.qlogo.cn/qqapp/1104662115/0C9B408A40341A699A65F3FFEBF77D19/100",
 "id": "3b888a7f-ff9f-4a6b-bff2-89a2b5b2f46e",
 "identity": "",
 "imQQ": "",
 "imWeibo": "",
 "imWeixin": "",
 "initSubscibeNum": 0,
 "integral": 0,
 "isAddress": 0,
 "j_PUSH_CODE": "",
 "jian": false,
 "level": 0,
 "listContent": [],
 "loginDate": "",
 "market": "",
 "messageCount": 0,
 "mobile": "3b888a7f-ff9f-4a6b-bff2-89a2b5b2f46e",
 "mySubscibeNum": 0,
 "newAuth": "",
 "newPassword": "",
 "occSelected": 0,
 "occupation": "",
 "password": "",
 "realName": "",
 "sex": "",
 "speciality": "",
 "state": "",
 "subscibeNum": 0,
 "terminal": "",
 "token": "",
 "uplevelPercent": "",
 "userName": "故梦",
 "validDate_M": "",
 "validDate_W": "",
 "validDate_Y": ""

 */
@property (nonatomic,copy) NSString *userName; /*<#id#>*/
@property (nonatomic,copy) NSString *headImg; /*<#id#>*/

@end

@interface ToUserModel : NSObject


/**
 "articleCount": 0,
 "attentionCount": 0,
 "attentioned": false,
 "auth": "",
 "bbsCount": 0,
 "birthday": "",
 "championM": false,
 "championW": false,
 "championY": false,
 "city": "",
 "content": "",
 "countryCode": "",
 "createDate": "",
 "dingYue": false,
 "email": "",
 "experience": 0,
 "fansCount": 0,
 "gag": false,
 "gagBeginDate": "",
 "gagEndDate": "",
 "headImg": "",
 "id": "",
 "identity": "",
 "imQQ": "",
 "imWeibo": "",
 "imWeixin": "",
 "initSubscibeNum": 0,
 "integral": 0,
 "isAddress": 0,
 "j_PUSH_CODE": "",
 "jian": false,
 "level": 0,
 "listContent": [],
 "loginDate": "",
 "market": "",
 "messageCount": 0,
 "mobile": "",
 "mySubscibeNum": 0,
 "newAuth": "",
 "newPassword": "",
 "occSelected": 0,
 "occupation": "",
 "password": "",
 "realName": "",
 "sex": "",
 "speciality": "",
 "state": "",
 "subscibeNum": 0,
 "terminal": "",
 "token": "",
 "uplevelPercent": "",
 "userName": "",
 "validDate_M": "",
 "validDate_W": "",
 "validDate_Y": ""
 */

@end

@interface CommentModel : NSObject


/**
 "appointNum": 0,
 "article": null,
 "bbsId": "aae0fcc8-d3f3-4558-befd-f98ff8f71d52",
 "content": "最美的花花",
 "createDate": "2016-09-23 08:46:36.0",
 "fnArticleAuthor": "",
 "fnAuditStatus": 0,
 "fnType": 0,
 "id": "a32b306f-3144-4559-93cd-1ee21a0f8b60",
 "isAppoint": 0,
 "recommend": 0,
 "toUser": {
 "articleCount": 0,
 "attentionCount": 0,
 "attentioned": false,
 "auth": "",
 "bbsCount": 0,
 "birthday": "",
 "championM": false,
 "championW": false,
 "championY": false,
 "city": "",
 "content": "",
 "countryCode": "",
 "createDate": "",
 "dingYue": false,
 "email": "",
 "experience": 0,
 "fansCount": 0,
 "gag": false,
 "gagBeginDate": "",
 "gagEndDate": "",
 "headImg": "",
 "id": "",
 "identity": "",
 "imQQ": "",
 "imWeibo": "",
 "imWeixin": "",
 "initSubscibeNum": 0,
 "integral": 0,
 "isAddress": 0,
 "j_PUSH_CODE": "",
 "jian": false,
 "level": 0,
 "listContent": [],
 "loginDate": "",
 "market": "",
 "messageCount": 0,
 "mobile": "",
 "mySubscibeNum": 0,
 "newAuth": "",
 "newPassword": "",
 "occSelected": 0,
 "occupation": "",
 "password": "",
 "realName": "",
 "sex": "",
 "speciality": "",
 "state": "",
 "subscibeNum": 0,
 "terminal": "",
 "token": "",
 "uplevelPercent": "",
 "userName": "",
 "validDate_M": "",
 "validDate_W": "",
 "validDate_Y": ""
 },
 "userBbs": null,
 "writer": {
 "articleCount": 0,
 "attentionCount": 0,
 "attentioned": false,
 "auth": "",
 "bbsCount": 0,
 "birthday": "",
 "championM": false,
 "championW": false,
 "championY": false,
 "city": "",
 "content": "",
 "countryCode": "",
 "createDate": "",
 "dingYue": false,
 "email": "",
 "experience": 0,
 "fansCount": 0,
 "gag": false,
 "gagBeginDate": "",
 "gagEndDate": "",
 "headImg": "http://q.qlogo.cn/qqapp/1104662115/0C9B408A40341A699A65F3FFEBF77D19/100",
 "id": "3b888a7f-ff9f-4a6b-bff2-89a2b5b2f46e",
 "identity": "",
 "imQQ": "",
 "imWeibo": "",
 "imWeixin": "",
 "initSubscibeNum": 0,
 "integral": 0,
 "isAddress": 0,
 "j_PUSH_CODE": "",
 "jian": false,
 "level": 0,
 "listContent": [],
 "loginDate": "",
 "market": "",
 "messageCount": 0,
 "mobile": "3b888a7f-ff9f-4a6b-bff2-89a2b5b2f46e",
 "mySubscibeNum": 0,
 "newAuth": "",
 "newPassword": "",
 "occSelected": 0,
 "occupation": "",
 "password": "",
 "realName": "",
 "sex": "",
 "speciality": "",
 "state": "",
 "subscibeNum": 0,
 "terminal": "",
 "token": "",
 "uplevelPercent": "",
 "userName": "故梦",
 "validDate_M": "",
 "validDate_W": "",
 "validDate_Y": ""
 }
 },
 */
@property (nonatomic,copy) NSString *content; /*<#id#>*/
@property (nonatomic,copy) NSString *createDate; /*<#id#>*/
@property (nonatomic,strong) WriterModel *writer; /*<#id#>*/
@property (nonatomic,strong) ToUserModel *toUser; /*<#id#>*/

@end
